set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
if-shell "ls /sys/class/power_supply/BAT* >/dev/null 2>&1 || pmset -g batt 2>/dev/null | grep -q InternalBattery" \
  'set -agF status-right "#{E:@catppuccin_status_battery}"'
